/**
 * Print events from stackspots.clar and the pot templates.
 * Status is derived from the event key (see EVENT_STATUS in pots.js).
 */
export const STACKSPOTS_EVENTS = {
  "admin added/updated": {
    source: "stackspots",
    kind: "platform",
    fields: ["event", "admin", "enable"],
  },
  "public pot deploy status updated": {
    source: "stackspots",
    kind: "platform",
    fields: ["event", "enable", "admin"],
  },
  "pot contract hash set": {
    source: "stackspots",
    kind: "platform",
    fields: ["event", "hash", "state"],
  },
  "pre-init": {
    source: "pot",
    kind: "pot",
    potStatus: "deployed",
    fields: [
      "event",
      "pot-cycle",
      "pot-min-amount",
      "pot-max-participants",
      "pot-name",
      "pot-type",
      "pot-is-init",
      "pot-admin",
      "pot-contract",
      "pot-owner",
      "pot-treasury",
      "funding-address",
    ],
  },
  "init-pot": {
    source: "pot",
    kind: "pot",
    potStatus: "joinable",
    fields: [
      "event",
      "owner",
      "pot-admin",
      "pot-treasury",
      "contract",
      "cycles",
      "type",
      "pot-reward-token",
      "min-amount",
      "max-participants",
      "pot-is-init",
    ],
  },
  "pot-registered": {
    source: "stackspots",
    kind: "pot",
    potStatus: "joinable",
    fields: [
      "event",
      "pot-id",
      "pot-address",
      "pot-owner",
      "pot-deploy-fee",
      "pot-name",
      "pot-type",
      "pot-cycles",
      "pot-reward-token",
      "pot-min-amount",
      "pot-max-participants",
      "origin-contract-sha-hash",
      "stacks-block-height",
      "burn-block-height",
    ],
  },
  "pot mint": {
    source: "stackspots",
    kind: "pot",
    potStatus: "joinable",
    fields: [
      "event",
      "contract-name",
      "recipient",
      "token-id",
      "tx-sender",
      "contract-caller",
      "platform-contracts-fee",
    ],
  },
  "join-pot": {
    source: "pot",
    kind: "pot",
    potStatus: "joinable",
    fields: ["event", "participant", "amount", "index"],
  },
  "join-pot-as-sponsor": {
    source: "pot",
    kind: "pot",
    potStatus: "joinable",
    fields: ["event", "sponsor", "amount", "sponsors-count"],
  },
  "start-stackspot-jackpot": {
    source: "pot",
    kind: "pot",
    potStatus: "started",
    fields: [
      "event",
      "pot-starter-principal",
      "pot-contract",
      "pot-treasury",
      "pot-participants",
      "pot-value",
      "pot-locked",
      "pot-lock-burn-height",
      "pot-cancelled",
    ],
  },
  "start-stackspot-crowdfund": {
    source: "pot",
    kind: "pot",
    potStatus: "started",
    fields: [
      "event",
      "pot-starter-principal",
      "pot-contract",
      "pot-treasury",
      "pot-participants",
      "pot-value",
      "pot-locked",
      "pot-lock-burn-height",
      "pot-cancelled",
    ],
  },
  "start-stackspot-sequential-pot": {
    source: "pot",
    kind: "pot",
    potStatus: "started",
    fields: [
      "event",
      "pot-starter-principal",
      "pot-contract",
      "pot-treasury",
      "pot-participants",
      "pot-value",
      "pot-locked",
      "pot-lock-burn-height",
      "pot-cancelled",
    ],
  },
  "stake-treasury": {
    source: "pot",
    kind: "pot",
    potStatus: "started",
    fields: ["event", "amount-ustx", "cycles", "first-reward-cycle", "unlock-cycle"],
  },
  "extend-stake": {
    source: "pot",
    kind: "pot",
    potStatus: "started",
    fields: ["event", "staked-cycles", "next-reward-cycle"],
  },
  "revoke-stake": {
    source: "pot",
    kind: "pot",
    potStatus: "started",
    fields: ["event"],
  },
  "pull-staking-rewards-cycle": {
    source: "pot",
    kind: "pot",
    potStatus: "started",
    fields: ["event", "reward-cycle", "earned", "paid", "withdrawal-request"],
  },
  "cancel-pot": {
    source: "pot",
    kind: "pot",
    potStatus: "cancelled",
    fields: ["event", "pot-cancelled", "pot-value", "pot-participants-count"],
  },
  "fall-back-cancel": {
    source: "pot",
    kind: "pot",
    potStatus: "cancelled",
    fields: [
      "event",
      "pot-cancelled",
      "pot-session-ended",
      "principals-returned",
      "pot-locked",
      "pot-value",
      "pot-participants-count",
      "defined-unlock-burn-height",
    ],
  },
  "claim-pot-reward": {
    source: "pot",
    kind: "pot",
    potStatus: "claimed",
    fields: [
      "event",
      "pot-participants-count",
      "pot-value",
      "pot-yield-amount",
      "winners-values",
      "starter-address",
      "starter-reward-amount",
      "claimer-address",
      "claimer-reward-amount",
      "pot-id",
      "pot-address",
      "pot-owner",
      "pot-name",
      "pot-type",
      "pot-cycle",
      "pot-reward-token",
      "pot-min-amount",
      "pot-max-participants",
      "origin-contract-sha-hash",
      "stacks-block-height",
      "burn-block-height",
      "lock-burn-height",
      "pot-cancelled",
    ],
  },
};
